export { createMcpServer, type McpServerOptions } from './create-mcp-server.ts';
export type {
  HostProblem,
  HostClient,
  HostClientFailure,
  SetUiLanguageRequest,
  SetUiLanguageResult,
  SystemStatus,
  UserPreferences,
  UiLocale,
  AddContextReferenceRequest,
  AddContextReferenceResult,
  AnalysisNoteMutationResult,
  AnalysisWorkspace,
  CreateAnalysisRecordRequest,
  CreateAnalysisRecordResult,
  CreateAnalysisNoteRequest,
  CreateAnalysisNoteResult,
  CreatePositionNoteRequest,
  DeleteAnalysisNoteRequest,
  CreateWorkingContextRequest,
  CreateWorkingContextResult,
  GetAnalysisWorkspaceRequest,
  ListWorkingContextsRequest,
  ListWorkingContextsResult,
  SearchInventoryRequest,
  SearchInventoryResult,
  SetWorkScopeResumeRequest,
  SetWorkScopeResumeResult,
  UpdateAnalysisScratchRequest,
  UpdateAnalysisScratchResult,
  UpdateAnalysisNoteRequest,
  WorkingContextWorkspace,
} from './host-client.ts';
