import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import openapiTS, { astToString, type OpenAPI3 } from 'openapi-typescript';

import { buildHost } from '../app/infrastructure/channels/api/index.ts';

const defaultOutputRoot = path.resolve('contracts', 'host');

export async function generateHostContract(
  outputRoot = defaultOutputRoot,
): Promise<void> {
  const productRelease = await readProductRelease();
  const unavailableUseCase = {
    execute: async (): Promise<never> => {
      throw new Error('Contract generation does not execute use cases.');
    },
  };
  const host = await buildHost({
    getSystemStatus: {
      execute: async () => ({
        state: 'ready',
        persistence: { schemaVersion: 1, dataRevision: 0 },
      }),
    },
    getDiagnosticSettings: unavailableUseCase,
    setDiagnosticLogLevel: unavailableUseCase,
    getDiagnosticReportManifest: unavailableUseCase,
    createDiagnosticReport: unavailableUseCase,
    getUserPreferences: {
      execute: async () => ({
        uiLocale: 'de-DE',
        preferenceRevision: 1,
        dataRevision: 0,
        updatedAt: '2026-01-01T00:00:00.000Z',
      }),
    },
    setUiLanguage: {
      execute: async () => ({
        changed: false,
        preferences: {
          uiLocale: 'de-DE',
          preferenceRevision: 1,
          dataRevision: 0,
          updatedAt: '2026-01-01T00:00:00.000Z',
        },
      }),
    },
    getAnalysisWorkspace: unavailableUseCase,
    updateAnalysisScratch: unavailableUseCase,
    createAnalysisRecord: unavailableUseCase,
    createAnalysisNote: unavailableUseCase,
    createPositionNote: unavailableUseCase,
    updateAnalysisNote: unavailableUseCase,
    deleteAnalysisNote: unavailableUseCase,
    searchInventory: unavailableUseCase,
    listWorkingContexts: unavailableUseCase,
    getWorkingContextWorkspace: unavailableUseCase,
    createWorkingContext: unavailableUseCase,
    addContextReference: unavailableUseCase,
    setWorkScopeResume: unavailableUseCase,
    events: {
      subscribe: () => ({ events: emptyEvents(), close: () => undefined }),
    },
    security: { hostToken: 'generated-contract-token' },
    productRelease,
    contractFingerprint: 'generated-at-build-time',
    correlationIdFactory: () => 'generated-correlation',
  });

  try {
    const document = sortObject(host.swagger()) as OpenAPI3;
    const canonical = `${JSON.stringify(document, null, 2)}\n`;
    const fingerprint = `sha256:${createHash('sha256').update(canonical).digest('hex')}`;
    const types = astToString(
      await openapiTS(document, {
        alphabetize: true,
        immutable: true,
        rootTypes: false,
      }),
    );

    const generatedDirectory = path.join(outputRoot, 'generated');
    await mkdir(generatedDirectory, { recursive: true });
    await Promise.all([
      writeFile(path.join(outputRoot, 'openapi.json'), canonical, 'utf8'),
      writeFile(
        path.join(generatedDirectory, 'openapi.ts'),
        `// Generated by tools/generate-host-contract.ts. Do not edit.\n${types}`,
        'utf8',
      ),
      writeFile(
        path.join(generatedDirectory, 'contract.ts'),
        `// Generated by tools/generate-host-contract.ts. Do not edit.\n` +
          `export const productRelease = ${JSON.stringify(productRelease)};\n` +
          `export const contractFingerprint = ${JSON.stringify(fingerprint)};\n`,
        'utf8',
      ),
    ]);
  } finally {
    await host.close();
  }
}

async function readProductRelease(): Promise<string> {
  const packageJson = JSON.parse(
    await readFile(path.resolve('package.json'), 'utf8'),
  ) as { version?: unknown };
  if (
    typeof packageJson.version !== 'string' ||
    packageJson.version.length === 0
  ) {
    throw new Error('package.json must contain a product version.');
  }
  return packageJson.version;
}

async function* emptyEvents(): AsyncIterable<never> {
  return;
}

function sortObject(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(sortObject);
  }
  if (typeof value !== 'object' || value === null) {
    return value;
  }
  return Object.fromEntries(
    Object.entries(value)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, nested]) => [key, sortObject(nested)]),
  );
}

if (isMainModule()) {
  await generateHostContract();
}

function isMainModule(): boolean {
  const entryPoint = process.argv[1];
  return (
    entryPoint !== undefined &&
    path.resolve(entryPoint) === fileURLToPath(import.meta.url)
  );
}
